name: Auto Merge

on:
  pull_request:
    types:
      - closed

jobs:
  auto-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Determine target branches
        id: branches
        run: |
          TARGET_BRANCH="${{ github.event.pull_request.base.ref }}"
          echo "::set-output name=target::$TARGET_BRANCH"

      - name: Propagate Changes
        run: |
          if [[ "$TARGET_BRANCH" == "release/"* ]]; then
            git checkout main
            git merge $TARGET_BRANCH --no-ff -m "Merge $TARGET_BRANCH into main"
            git push origin main

            git checkout develop
            git merge $TARGET_BRANCH --no-ff -m "Merge $TARGET_BRANCH into develop"
            git push origin develop
          elif [[ "$TARGET_BRANCH" == "hotfix/"* ]]; then
            VERSION=$(echo $TARGET_BRANCH | cut -d'/' -f2)
            git checkout main
            git merge $TARGET_BRANCH --no-ff -m "Merge $TARGET_BRANCH into main"
            git push origin main

            git checkout develop
            git merge $TARGET_BRANCH --no-ff -m "Merge $TARGET_BRANCH into develop"
            git push origin develop
          fi
