name: PR Validation

on:
  pull_request:
    branches:
      - main
      - develop
      - release/*
      - hotfix/*

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build CascadingMergesForGitHubActions.sln --no-restore --configuration Release

      - name: Run Tests
        run: dotnet test CascadingMergesForGitHubActions.sln --no-build --verbosity normal
